nameSuffix: "-backend"
namespace: whereami-grpc-backend
commonLabels:
  app: whereami-grpc-backend
resources:
- ../base
patches:
- path: cm-flag.yaml
  target:
    kind: ConfigMap
- path: service-type.yaml
  target:
    kind: Service
- path: deployment-bypass.yaml
  target:
    kind: Deployment
